
import { Food } from "./app/shared/models/Food";
import { Tag } from "./app/shared/models/Tag";


export const sample_foods:Food[]=[

    {
        id:'1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 160,
        favorite: true,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'assets/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:'2',
        name: 'Meatball',
        price: 180,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'assets/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
      },
      {
        id:'3',
        name: 'Hamburger',
        price: 35,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'assets/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
      },
      {
        id:'4',
        name: 'Fried Potatoes',
        price: 50,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'assets/food-4.jpg',
        tags: ['FastFood', 'Fry'],
      },
      {
        id:'5',
        name: 'Yougart Soup',
        price: 70,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'assets/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
      },
      {
        id:'6',
        name: 'Vegetables Pizza',
        price: 120,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:'7',
        name: 'Paneer Tika',
        price: 150,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian'],
        stars: 4.0,
        imageUrl: 'assets/food-7.jpg',
        tags: ['FastFood', 'Burger', 'Lunch'],
      },
      {
        id:'8',
        name: 'Vegetables Magento Pizza',
        price: 100,
        cookTime: '45-50',
        favorite: false,
        origins: ['indian'],
        stars: 4.0,
        imageUrl: 'assets/food-8.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:'9',
        name: 'Til pitha',
        price: 25,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/9.jpg',
        tags: [ 'Sweet dish'],
      },
      {
        id:'10',
        name: 'Aloo-Pitika',
        price: 15,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/10.jpg',
        tags: ['Lunch'],
      },
      {
        id:'11',
        name: 'Lai-xaak-Gahori',
        price: 200,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/11.jpg',
        tags: ['Lunch','Non-veg'],
      },
      {
        id:'12',
        name: 'Baah-Gaaj-Bhoot-jolokia-di-Gahori',
        price: 280,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/12.jpg',
        tags: ['Lunch','Non-Veg'],
      },
      {
        id:'13',
        name: 'Dhekia-Bhaji',
        price: 30,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian'],
        stars: 4.0,
        imageUrl: 'assets/13.jpg',
        tags: ['Lunch','Veg'],
      },
      {
        id:'14',
        name: 'Doi-Chira',
        price: 50,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/14.jpg',
        tags: ['Breakfast','Sweet dish'],
      },
      {
        id:'15',
        name: 'Haah-Joha-Kumura',
        price: 250,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/15.jpg',
        tags: ['Non-veg', 'Dinner'],
      },
      {
        id:'16',
        name: 'Khulasaporir-pitha',
        price: 25,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/16.jpg',
        tags: ['Breakfast', 'Lunch'],
      },
      {
        id:'17',
        name: 'Koldil-Murgi',
        price: 150,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/17.jpg',
        tags: ['Non-Veg', 'Dinner'],
      },
      {
        id:'18',
        name: 'Kosuthuri-kon-bilahi',
        price: 50,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/18.jpg',
        tags: ['Non-Veg', 'Dinner'],
      },
      {
        id:'19',
        name: 'Kothalguti-Pitika',
        price: 25,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/19.jpg',
        tags: ['Veg', 'Lunch'],
      },
      {
        id:'20',
        name: 'Maah-Proxador-Khar',
        price: 30,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/20.jpg',
        tags: ['Veg', 'Lunch'],
      },
      {
        id:'21',
        name: 'Maasor-Tenga',
        price: 100,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/21.jpg',
        tags: ['Non-Veg', 'Dinner', 'Lunch'],
      },
      {
        id:'22',
        name: 'Mati-Dail-khar',
        price: 45,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/22.jpg',
        tags: ['Veg', 'Dinner', 'Lunch'],
      },
      {
        id:'23',
        name: 'Outenga-Dail',
        price: 35,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/23.jpg',
        tags: ['Veg', 'Dinner', 'Lunch'],
      },
      {
        id:'24',
        name: 'Patot-diya-maas',
        price: 70,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/24.jpg',
        tags: ['Non-Veg', 'Lunch'],
      },
      {
        id:'25',
        name: 'Payokh',
        price: 80,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/25.jpg',
        tags: ['Sweet dish', 'Lunch'],
      },
      {
        id:'26',
        name: 'Poita-Bhat',
        price: 40,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/26.jpg',
        tags: ['Sweet dish', 'Lunch'],
      },
      {
        id:'27',
        name: 'Tekeli-pitha',
        price: 60,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/27.jpg',
        tags: ['Sweet dish', 'Lunch'],
      },
      {
        id:'28',
        name: 'Til-Diya-Murgi',
        price: 350,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','Assam'],
        stars: 4.0,
        imageUrl: 'assets/28.jpg',
        tags: ['Non-Veg','Dinner'],
      }

]

export const sample_tags:Tag[] = [

  {name:'All', count: 28},
  {name:'Veg', count: 5},
  {name:'Non-Veg', count: 6},
  {name:'Sweet dish', count: 5},
  {name:'Lunch', count: 19},
  {name:'Dinner', count: 7},
  {name:'FastFood', count: 6}
]
